# Generated by Django 5.0.1 on 2024-01-26 17:24

import django.db.models.deletion
import game_keys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('price', models.CharField(max_length=5, verbose_name='Стоимость')),
                ('activation', models.CharField(choices=[('Steam', 'Steam'), ('EA', 'EA'), ('Ubisoft', 'Ubisoft'), ('Epic Games', 'Epic Games'), ('GOG', 'GOG'), ('Rockstar', 'Rockstar')], max_length=20, verbose_name='Активация')),
                ('region', models.CharField(choices=[('Весь мир', 'Весь мир'), ('Россия/СНГ', 'Россия/СНГ'), ('Россия', 'Россия')], max_length=20, verbose_name='Регион')),
                ('genre', models.CharField(choices=[('Экшен', 'Экшен'), ('Шутер', 'Шутер'), ('Стратегия', 'Стратегия'), ('Инди', 'Инди'), ('Приключение', 'Приключение'), ('Симулятор', 'Симулятор'), ('Ролевая игра', 'Ролевая игра'), ('Файтинг', 'Файтинг')], max_length=40, verbose_name='Жанр')),
                ('publisher', models.CharField(max_length=20, verbose_name='Издатель')),
                ('developer', models.CharField(max_length=15, verbose_name='Разработчик')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('ea_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на EA')),
                ('rockstar_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Rockstar')),
                ('steam_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Steam')),
                ('gog_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на GOG')),
                ('epic_games_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на EpicGames')),
                ('ubisoft_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Ubisoft')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение продукта')),
                ('catalog_image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Изображение для каталога')),
                ('image_screen_1', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 1')),
                ('image_screen_2', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 2')),
                ('image_screen_3', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 3')),
                ('image_screen_4', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 4')),
                ('image_screen_5', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 5')),
                ('image_screen_6', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 6')),
                ('image_screen_7', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 7')),
                ('image_screen_8', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 8')),
                ('image_screen_9', models.ImageField(blank=True, null=True, upload_to=game_keys.models.game_screenshot_upload_path, verbose_name='Изображение для Скриншота 9')),
                ('description', models.TextField(verbose_name='Описание')),
                ('num_keys', models.PositiveIntegerField(default=0, verbose_name='Количество ключей')),
            ],
            options={
                'verbose_name': 'Игру',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ')),
                ('status', models.CharField(choices=[('Не активен', 'Не активен'), ('Активен', 'Активен')], default='Не активен', max_length=10, verbose_name='Статус')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='game_keys.gameitem')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
        migrations.CreateModel(
            name='GameScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.FileField(blank=True, null=True, upload_to='scripts/', verbose_name='Путь к скрипту')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='game_keys.gameitem')),
            ],
            options={
                'verbose_name': 'Эффект шрифта',
                'verbose_name_plural': 'font_effects',
            },
        ),
    ]
