# Generated by Django 5.0.1 on 2024-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescript',
            name='script_path',
            field=models.FileField(blank=True, null=True, upload_to='static/js/', verbose_name='Путь к скрипту'),
        ),
    ]
