# Generated by Django 5.0.1 on 2024-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0002_alter_gamescript_script_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescript',
            name='script_path',
            field=models.FileField(blank=True, null=True, upload_to='scripts/', verbose_name='Путь к скрипту'),
        ),
    ]
