# Generated by Django 5.0.1 on 2024-01-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0003_alter_gamescript_script_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScript',
        ),
    ]
