# Generated by Django 5.0.1 on 2024-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0004_delete_gamescript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
