# Generated by Django 5.0.1 on 2024-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0005_alter_gameitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
