# Generated by Django 5.0.1 on 2024-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0006_alter_gameitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
