# Generated by Django 5.0.1 on 2024-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0007_gameitem_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='developer',
            field=models.CharField(max_length=25, verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='publisher',
            field=models.CharField(max_length=25, verbose_name='Издатель'),
        ),
    ]
