# Generated by Django 5.0.1 on 2024-02-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0008_alter_gameitem_developer_alter_gameitem_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('Экшен', 'Экшен'), ('Шутер', 'Шутер'), ('Стратегия', 'Стратегия'), ('Инди', 'Инди'), ('Приключение', 'adventure'), ('Симулятор', 'Симулятор'), ('Ролевая игра', 'Ролевая игра'), ('Файтинг', 'Файтинг')], max_length=40, verbose_name='Жанр'),
        ),
    ]
