# Generated by Django 5.0.1 on 2024-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0011_alter_gameitem_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('Action', 'Экшен'), ('Shooter', 'Шутер'), ('Strategy', 'Стратегия'), ('Indie', 'Инди'), ('Adventure', 'Приключение'), ('Simulator', 'Симулятор'), ('Role-playing', 'Ролевая игра'), ('Fighting', 'Файтинг')], max_length=40, verbose_name='Жанр'),
        ),
    ]
