# Generated by Django 5.0.1 on 2024-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0012_alter_gameitem_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Shooter', 'Shooter'), ('Strategy', 'Strategy'), ('Indie', 'Indie'), ('Adventure', 'Adventure'), ('Simulator', 'Simulator'), ('Role-playing', 'Role-playing'), ('Fighting', 'Fighting')], max_length=40, verbose_name='Жанр'),
        ),
    ]
