# Generated by Django 5.0.1 on 2024-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0013_alter_gameitem_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг')], max_length=40, verbose_name='Жанр'),
        ),
    ]
