# Generated by Django 5.0.1 on 2024-02-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0016_gameitem_slug_alter_gameitem_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Большое изображение для слайдера')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='game_keys.gameitem')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
            },
        ),
    ]
