# Generated by Django 5.0.1 on 2024-02-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0017_sliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='image',
            new_name='slider_image',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='game',
            new_name='slider_title',
        ),
    ]
