# Generated by Django 5.0.1 on 2024-02-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0018_rename_image_sliderimage_slider_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='slider_title',
            new_name='game',
        ),
    ]
