# Generated by Django 5.0.1 on 2024-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0021_alter_gameitem_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='activation',
            field=models.CharField(choices=[('Steam', 'Steam'), ('EA', 'EA'), ('Ubisoft', 'Ubisoft'), ('Epic Games', 'Epic Games'), ('GOG', 'GOG'), ('Rockstar', 'Rockstar'), ('Microsoft Store', 'Microsoft Store'), ('VK Play', 'VK Play')], max_length=20, verbose_name='Активация'),
        ),
    ]
