# Generated by Django 5.0.1 on 2024-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0022_alter_gameitem_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='vk_play_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Ubisoft'),
        ),
    ]
