# Generated by Django 5.0.1 on 2024-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0023_gameitem_vk_play_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameitem',
            name='genre',
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='vk_play_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на VK Play'),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='game_keys.genre', verbose_name='Жанры'),
        ),
    ]
