# Generated by Django 5.0.1 on 2024-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0024_genre_remove_gameitem_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameitem',
            name='genres',
        ),
        migrations.AddField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], default=0, max_length=40, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
