# Generated by Django 5.0.1 on 2024-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0025_remove_gameitem_genres_gameitem_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='genre_1',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], default=1, max_length=40, verbose_name='Жанр 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameitem',
            name='genre_2',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], default=0, max_length=40, verbose_name='Жанр 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameitem',
            name='genre_3',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], default=0, max_length=40, verbose_name='Жанр 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameitem',
            name='genre_4',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], default=0, max_length=40, verbose_name='Жанр 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Основной жанр'),
        ),
    ]
