# Generated by Django 5.0.1 on 2024-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0026_gameitem_genre_1_gameitem_genre_2_gameitem_genre_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Основной жанр'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='genre_1',
            field=models.CharField(blank=True, choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Жанр 1'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Жанр 2'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='genre_3',
            field=models.CharField(blank=True, choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Жанр 3'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='genre_4',
            field=models.CharField(blank=True, choices=[('action', 'Экшен'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('indie', 'Инди'), ('adventure', 'Приключение'), ('simulator', 'Симулятор'), ('role-playing', 'Ролевая игра'), ('fighting', 'Файтинг'), ('sandbox', 'Песочница'), ('rpg', 'РПГ'), ('survival', 'Выживание')], max_length=40, verbose_name='Жанр 4'),
        ),
    ]
