# Generated by Django 5.0.1 on 2024-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0027_alter_gameitem_genre_alter_gameitem_genre_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='region',
            field=models.CharField(choices=[('Region Free', 'Region Free'), ('Россия/СНГ', 'Россия/СНГ'), ('Россия', 'Россия')], max_length=20, verbose_name='Регион'),
        ),
    ]
