# Generated by Django 5.0.1 on 2024-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0028_alter_gameitem_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='region',
            field=models.CharField(choices=[('Весь мир', 'Весь мир'), ('Россия/СНГ', 'Россия/СНГ'), ('Россия', 'Россия')], max_length=20, verbose_name='Регион'),
        ),
    ]
