# Generated by Django 5.0.1 on 2024-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0032_alter_gameitem_genre_alter_gameitem_genre_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='app_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
