# Generated by Django 5.0.1 on 2024-10-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0033_gameitem_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='app_id',
            field=models.IntegerField(default=0, verbose_name='ID игры'),
        ),
    ]
