# Generated by Django 5.0.1 on 2024-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0034_alter_gameitem_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='is_editors_choice',
            field=models.BooleanField(default=False, verbose_name='Выбор редакции'),
        ),
    ]
