# Generated by Django 5.0.1 on 2024-11-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_keys', '0036_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='game',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
